/** Shared Mermaid theme aligned with Fonora research / grammar surfaces. */
export const MERMAID_INIT = {
  startOnLoad: false,
  theme: 'base',
  themeVariables: {
    fontFamily: 'ui-monospace, Menlo, monospace',
    fontSize: '14px',
    background: '#faf8f5',
    mainBkg: '#eef6f1',
    secondBkg: '#f5f1eb',
    tertiaryBkg: '#faf8f5',
    primaryColor: '#eef6f1',
    primaryTextColor: '#1b4332',
    primaryBorderColor: '#b7d4c4',
    secondaryColor: '#f5f1eb',
    secondaryTextColor: '#3d3832',
    secondaryBorderColor: '#e0dad2',
    tertiaryColor: '#faf8f5',
    tertiaryTextColor: '#4a4540',
    tertiaryBorderColor: '#e8e2da',
    lineColor: '#c4bbb0',
    textColor: '#3d3832',
    nodeTextColor: '#1b4332',
    nodeBorder: '#b7d4c4',
    clusterBkg: '#faf8f5',
    clusterBorder: '#e0dad2',
    titleColor: '#2d6a4f',
    edgeLabelBackground: '#faf8f5',
  },
  securityLevel: 'loose',
};
